/**
 * Public Supabase access layer.
 * Import services/hooks from here — never the raw client.
 */

export type {
  Database,
  TableName,
  TableRow,
  TableInsert,
  TableUpdate,
  RpcName,
  RpcArgs,
  RpcReturns,
  PublicTables,
  Json,
  UserRole as DbUserRole,
  UserStatus as DbUserStatus,
  CreateRepresentativePayload,
  CompanyAccessStatus,
  WorkGroupStatus,
  VoteMode,
  PollStatus,
  MessengerPlatform,
  BotStatus,
  MessageSource,
  DeliveryStatus,
  RelayStatus,
} from './types/database'

export {
  authService,
  companyLookupService,
  normalizeInnDigits,
  directoryService,
  cabinetPollsMetaService,
  staffService,
  storageService,
  STORAGE_BUCKETS,
  rpcService,
  dataService,
  registrationsService,
  levelsService,
  companiesService,
  representativesService,
  materialsService,
  materialAccessService,
  documentsService,
  workGroupsService,
  workGroupMembersService,
  workGroupLinksService,
  messengerConnectionsService,
  messagesService,
  auditService,
  AUDIT_EXPORT_MAX_ROWS,
  pollsService,
  slugifyTitle,
} from './services'
export type {
  AuthProfile,
  MemberMembership,
  SignInInput,
  SignUpInput,
  CompanyByInn,
  DirectoryCompany,
  DirectoryRepresentative,
  CabinetPollAccessHint,
  StaffUser,
  PromoteStaffInput,
  UpdateStaffInput,
  StorageBucket,
  UploadFileInput,
  UploadFileResult,
  RegistrationApplication,
  RegistrationListFilters,
  RegistrationRepresentative,
  RepresentativeOption,
  CompanyOption,
  ParticipationLevel,
  ParticipationLevelInput,
  ParticipationLevelUsage,
  LevelsListFilters,
  Company,
  CompanyInput,
  CompanyLevelRef,
  CompaniesListFilters,
  Representative,
  RepresentativeInput,
  RepresentativeCompanyRef,
  RepresentativesListFilters,
  MaterialSection,
  MaterialSectionInput,
  MaterialLevelRef,
  MaterialsListFilters,
  CabinetMaterial,
  MaterialAccessMode,
  BulkMaterialAccessInput,
  MaterialDocument,
  MaterialDocumentUploadInput,
  WorkGroup,
  WorkGroupInput,
  WorkGroupsListFilters,
  WorkGroupMember,
  WorkGroupMessengerConnection,
  WorkGroupRepresentativeRef,
  WorkGroupMemberCandidate,
  WorkGroupMembersListFilters,
  BulkAddWorkGroupMembersResult,
  WorkGroupMemberRepresentative,
  WorkGroupLink,
  WorkGroupLinkExternalInput,
  WorkGroupLinkFileInput,
  WorkGroupLinkUpdateInput,
  MessengerConnection,
  MessengerConnectionInput,
  Message,
  MessageRelay,
  MessageWorkGroupRef,
  MessagesListFilters,
  MessagesListResult,
  AuditLogEntry,
  AuditLogActor,
  AuditLogInput,
  AuditLogListFilters,
  AuditLogListResult,
  Poll,
  PollInput,
  PollOption,
  PollLevelRef,
  PollsListFilters,
  CabinetPoll,
  MemberPollVote,
  PollResults,
  PollResultsOption,
  PollVoteRow,
} from './services'

export type { Session, User, AuthChangeEvent } from '@supabase/supabase-js'

export { useSupabaseQuery, useSupabaseMutation, queryKeys } from './hooks'

export { unwrap, unwrapMaybe, fromSupabaseError, runSupabase } from './lib/helpers'
export { redactSecrets, sanitizeForLog, safeErrorMessage } from './lib/security'
